$(call inherit-product, $(SRC_TARGET_DIR)/product/full_S96Pro.mk)


PRODUCT_DEVICE := S96Pro
PRODUCT_NAME := ZN129T_RU
PRODUCT_BRAND := DOOGEE
PRODUCT_MODEL := S96Pro
PRODUCT_MANUFACTURER := DOOGEE
PRODUCT_BOARD := mt6785
